/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_qqgame_client_scene_model_GameModel */

#ifndef _Included_com_tencent_qqgame_client_scene_model_GameModel
#define _Included_com_tencent_qqgame_client_scene_model_GameModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_qqgame_client_scene_model_GameModel
 * Method:    gamePatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_qqgame_client_scene_model_GameModel_gamePatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
